package org.yourorghere;

import com.sun.opengl.util.Animator;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

public class SimpleGLCanvas extends JFrame {
    

    static {
        // When using a GLCanvas, we have to set the Popup-Menues to be HeavyWeight,
        // so they display properly on top of the GLCanvas
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
    }
    
    private Animator animator;
    private static int typeForm = 0;
    private static int typeTransform = -1;

    /** Creates new form MainFrame */
    public SimpleGLCanvas() {
        initComponents();
        setTitle("3D-projeto");

        canvas.addGLEventListener(new GLRenderer());
        animator = new Animator(canvas);
        animator.start();

        // This is a workaround for the GLCanvas not adjusting its size, when the frame is resized.
        canvas.setMinimumSize(new Dimension());  
        
        
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
    }

    @Override
    public void setVisible(boolean show){
        if(!show)
            animator.stop();
        super.setVisible(show);
        if(!show)
            animator.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new JRadioButton();
        JLabel label = new JLabel();
        canvas = new GLCanvas(createGLCapabilites());
        jToggleButton1 = new JToggleButton();
        jLabel1 = new JLabel();
        piramideObj = new JRadioButton();
        cuboObj = new JRadioButton();
        coneObj = new JRadioButton();
        cilindroObj = new JRadioButton();
        labelTransf = new JLabel();
        rotacao = new JRadioButton();
        translacao = new JRadioButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        label.setText("Projeto 3D - Computação Gráfica");

        jToggleButton1.setText("Clique");
        jToggleButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Informe o objeto");

        piramideObj.setText("Pirâmide");

        cuboObj.setText("Cubo");

        coneObj.setText("Cone");

        cilindroObj.setText("Cilindro");

        labelTransf.setText("Transformação");

        rotacao.setText("Rotação");

        translacao.setText("Translação");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jToggleButton1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(piramideObj)
                            .addComponent(cuboObj)
                            .addComponent(coneObj)
                            .addComponent(cilindroObj)
                            .addComponent(labelTransf)
                            .addComponent(rotacao)
                            .addComponent(translacao))
                        .addGap(46, 46, 46)
                        .addComponent(canvas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(canvas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(piramideObj)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(cuboObj)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(coneObj)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(cilindroObj)
                        .addGap(18, 18, 18)
                        .addComponent(labelTransf)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(rotacao)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(translacao)
                        .addGap(163, 163, 163)
                        .addComponent(jToggleButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Button to create a graph
    private void jToggleButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        /*valueX = Float.parseFloat(textX.getText());
        valueY = Float.parseFloat(textY.getText());
        valueZ = Float.parseFloat(textZ.getText());*/
        
        if (piramideObj.isSelected() == true && cuboObj.isSelected() == true) {
            // Criar piramide e cubo
            typeForm = 5;
            if(rotacao.isSelected()) {
               // ROTAÇÃO
                typeTransform = 1;
            }else if (translacao.isSelected()){
                // TRANSLAÇÃO
                typeTransform = 0;
            }
            System.out.println("Pirâmide e CUBO");
        }
        
        else if(piramideObj.isSelected() == true && coneObj.isSelected() == true) {
            // Criar piramide e cone
            typeForm = 6;
        }
        
        else if(piramideObj.isSelected() == true && cilindroObj.isSelected() == true) {
            // Criar piramide e cilindro
            typeForm = 7;
        }
        
        else if(cuboObj.isSelected() == true && coneObj.isSelected() == true) {
            // Criar cubo e cone
            typeForm = 8;
        }
        
        else if(cuboObj.isSelected() == true && cilindroObj.isSelected() == true) {
            // Criar cubo e cilindro
            typeForm = 9;
        }
        
        else if(cilindroObj.isSelected() == true && coneObj.isSelected() == true) {
            // criar Cilindro  e cone
            typeForm = 10;
        }
        
        else if (piramideObj.isSelected() == true) {
            // criar piramide...
            typeForm = 1;
            if(rotacao.isSelected()) {
                // ROTAÇÃO
                typeTransform = 1;
            }else if (translacao.isSelected()) {
                // TRANSLAÇÃO
                typeTransform = 0;
            }

            System.out.println("o objeto foi "+ piramideObj.getText());
        }
        
        else if (cuboObj.isSelected()) {
            typeForm = 2;
            if(rotacao.isSelected()) {
               // ROTAÇÃO
                typeTransform = 1;
            }else if (translacao.isSelected()){
                // TRANSLAÇÃO
                typeTransform = 0;
            }
        }
        
        else if (coneObj.isSelected()) {
            // criar piramide...
            typeForm = 3;
            if(rotacao.isSelected()) {
                // ROTAÇÃO
                typeTransform = 1;
            }else if (translacao.isSelected()){
                // TRANSLAÇÃO
                typeTransform = 0;
            }
            System.out.println("o objeto foi "+ coneObj.getText());
        }
        
        else if (cilindroObj.isSelected()) {
            // criar piramide...
            typeForm = 4;
            if(rotacao.isSelected()) {
                // ROTAÇÃO
                typeTransform = 1;
            }else if (translacao.isSelected()){
                // TRANSLAÇÃO
                typeTransform = 0;
            }
            System.out.println("o objeto foi "+ cilindroObj.getText());
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * Called from within initComponents().
     * hint: to customize the generated code choose 'Customize Code' in the contextmenu
     * of the selected UI Component you wish to cutomize in design mode.
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites() {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        capabilities.setNumSamples(2);
        capabilities.setSampleBuffers(true);
        
        return capabilities;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable() {
            public void run() {

                // switch to system l&f for native font rendering etc.
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch(Exception ex) {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }

                SimpleGLCanvas frame = new SimpleGLCanvas();
                frame.setVisible(true);
                
                
            }
        });
    }
    
    public static int getTypeForm() {
        return typeForm;
    }
    
    public static int getTypeTransform() {
        return typeTransform;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GLCanvas canvas;
    private JRadioButton cilindroObj;
    private JRadioButton coneObj;
    private JRadioButton cuboObj;
    private JLabel jLabel1;
    private JRadioButton jRadioButton1;
    private JToggleButton jToggleButton1;
    private JLabel labelTransf;
    private JRadioButton piramideObj;
    private JRadioButton rotacao;
    private JRadioButton translacao;
    // End of variables declaration//GEN-END:variables

}
